"""Day 10: Production LLM Structured Outputs & Tool Calling Validation Engine.

This module implements an enterprise-grade LLM structured outputs and tool calling engine:
1. Generic API Response Envelopes (Generic[T]) with strong runtime typing.
2. Composable Tool Calling schemas compatible with OpenAI / Google Gemini Function Calling.
3. Strict Pydantic V2 validation with error extraction for automated LLM self-correction.
4. Annotated types with custom AfterValidators for SQL query sanitization.
"""

import json
import logging
import re
from datetime import datetime, timezone
from typing import Annotated, Any, Dict, Generic, List, Literal, Optional, TypeVar
from uuid import UUID, uuid4

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    Field,
    ValidationError,
)


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("ToolCallingEngine")


# =====================================================================
# 1. ANNOTATED VALIDATORS FOR SECURITY & SANITIZATION
# =====================================================================
def validate_safe_sql_query(query: str) -> str:
    """Ensure generated SQL queries are strictly read-only SELECT statements."""
    prohibited_keywords = ["DROP", "DELETE", "UPDATE", "INSERT", "ALTER", "TRUNCATE", "GRANT"]
    normalized = query.strip()

    if not normalized.upper().startswith("SELECT"):
        raise ValueError("Security Violation: LLM generated a non-SELECT query statement")

    for keyword in prohibited_keywords:
        # Use regex boundary matching to prevent matching column names like 'updated_at'
        if re.search(rf"\b{keyword}\b", normalized, flags=re.IGNORECASE):
            raise ValueError(f"Security Violation: Query contains prohibited keyword '{keyword}'")

    return normalized


SafeReadOnlySQL = Annotated[
    str,
    Field(min_length=10, max_length=2000, description="Read-only SQL SELECT statement"),
    AfterValidator(validate_safe_sql_query),
]


# =====================================================================
# 2. TOOL CALL PARAMETER DEFINITIONS
# =====================================================================
class DatabaseQueryTool(BaseModel):
    """Schema for executing SQL queries generated by LLMs."""

    model_config = ConfigDict(extra="forbid", strict=True)

    query: SafeReadOnlySQL
    database_target: Literal["analytics_replica", "users_replica"] = Field(
        description="Target read replica cluster"
    )
    timeout_seconds: float = Field(default=5.0, ge=0.5, le=30.0)


class VectorSearchTool(BaseModel):
    """Schema for querying enterprise vector databases for RAG."""

    model_config = ConfigDict(extra="forbid", strict=True)

    query_text: str = Field(min_length=3, max_length=1000)
    top_k: int = Field(default=5, ge=1, le=50)
    similarity_threshold: float = Field(default=0.75, ge=0.0, le=1.0)
    collection_name: Literal["support_docs", "engineering_specs"] = "support_docs"


# =====================================================================
# 3. GENERIC API RESPONSE ENVELOPE (Generic[T])
# =====================================================================
T = TypeVar("T")


class APIEnvelope(BaseModel, Generic[T]):
    """Standardized API envelope for all backend and AI microservice responses."""

    trace_id: UUID = Field(default_factory=uuid4)
    success: bool
    data: Optional[T] = None
    errors: List[Dict[str, Any]] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @classmethod
    def ok(cls, payload: T) -> "APIEnvelope[T]":
        return cls(success=True, data=payload)

    @classmethod
    def fail(cls, errors: List[Dict[str, Any]]) -> "APIEnvelope[None]":
        return cls(success=False, data=None, errors=errors)


# =====================================================================
# 4. LLM TOOL REGISTRY & RUNTIME DISPATCH ENGINE
# =====================================================================
class ToolExecutionEngine:
    """Generates OpenAI/Gemini schemas and validates model responses."""

    def __init__(self) -> None:
        self._registry: Dict[str, type[BaseModel]] = {
            "execute_database_query": DatabaseQueryTool,
            "query_vector_index": VectorSearchTool,
        }

    def export_openai_tools(self) -> List[Dict[str, Any]]:
        """Export tool definitions to OpenAI / Google Gemini function schemas."""
        tools = []
        for tool_name, model_cls in self._registry.items():
            tools.append(
                {
                    "type": "function",
                    "function": {
                        "name": tool_name,
                        "description": model_cls.__doc__ or "",
                        "parameters": model_cls.model_json_schema(),
                    },
                }
            )
        return tools

    def validate_and_dispatch(
        self, tool_name: str, raw_arguments_json: str
    ) -> APIEnvelope[Any]:
        """Parse, validate, and execute LLM tool call arguments with error diagnostics."""
        model_cls = self._registry.get(tool_name)
        if not model_cls:
            return APIEnvelope.fail(
                [{"field": "tool_name", "error": f"Tool '{tool_name}' not registered in engine"}]
            )

        # 1. Parse JSON string
        try:
            parsed_args = json.loads(raw_arguments_json)
        except json.JSONDecodeError as err:
            return APIEnvelope.fail(
                [{"field": "raw_arguments", "error": f"Malformed JSON string: {err.msg}"}]
            )

        # 2. Strict Pydantic V2 Validation
        try:
            validated_tool_call = model_cls.model_validate(parsed_args)
            logger.info(f"Tool call '{tool_name}' validated successfully: {validated_tool_call}")
            # Dispatch to mock backend service
            execution_result = self._mock_execute(tool_name, validated_tool_call)
            return APIEnvelope.ok(execution_result)
        except ValidationError as err:
            # Extract actionable error feedback for LLM self-correction
            diagnostic_errors = []
            for e in err.errors():
                diagnostic_errors.append(
                    {
                        "field": ".".join(str(loc) for loc in e["loc"]),
                        "input": e.get("input"),
                        "message": e["msg"],
                    }
                )
            logger.warning(
                f"LLM tool call validation failed for '{tool_name}'. "
                f"Extracted {len(diagnostic_errors)} errors for self-correction feedback."
            )
            return APIEnvelope.fail(diagnostic_errors)

    def _mock_execute(self, tool_name: str, tool_args: BaseModel) -> Dict[str, Any]:
        """Simulate execution on backend microservices."""
        if tool_name == "execute_database_query":
            return {
                "rows_returned": 2,
                "records": [
                    {"id": 101, "total_spend": 12500.50},
                    {"id": 102, "total_spend": 8940.00},
                ],
            }
        elif tool_name == "query_vector_index":
            return {
                "hits": 3,
                "documents": [
                    {"doc_id": "doc_01", "score": 0.89, "snippet": "HNSW index traversal guide."},
                ],
            }
        return {}


# =====================================================================
# SIMULATION & VERIFICATION RUNNER
# =====================================================================
def run_simulation() -> None:
    logger.info("Initializing ToolExecutionEngine...")
    engine = ToolExecutionEngine()

    # 1. Export OpenAPI/JSON Schema for LLM Function Calling
    tool_schemas = engine.export_openai_tools()
    print("=" * 65)
    print("1. GENERATED OPENAI / GEMINI FUNCTION CALLING SCHEMA:")
    print("=" * 65)
    print(json.dumps(tool_schemas[0], indent=2))

    # 2. Scenario A: Valid LLM Tool Call
    print("\n" + "=" * 65)
    print("2. SCENARIO A: VALID DATABASE QUERY TOOL CALL")
    print("=" * 65)
    valid_args = json.dumps(
        {
            "query": "SELECT user_id, sum(amount) FROM transactions GROUP BY user_id LIMIT 10",
            "database_target": "analytics_replica",
            "timeout_seconds": 10.0,
        }
    )
    res_a = engine.validate_and_dispatch("execute_database_query", valid_args)
    print(f"[*] Response Status: success={res_a.success}")
    print(f"[*] Response Payload: {res_a.data}")

    # 3. Scenario B: Malicious / Dangerous LLM SQL Injection Attempt
    print("\n" + "=" * 65)
    print("3. SCENARIO B: SECURITY VIOLATION INTERCEPTION")
    print("=" * 65)
    malicious_args = json.dumps(
        {
            "query": "DELETE FROM users WHERE is_active = false",
            "database_target": "users_replica",
            "timeout_seconds": 5.0,
        }
    )
    res_b = engine.validate_and_dispatch("execute_database_query", malicious_args)
    print(f"[*] Response Status: success={res_b.success}")
    print(f"[*] Security Errors Intercepted: {res_b.errors}")

    # 4. Scenario C: Hallucinated Field & Out-Of-Bounds Parameters
    print("\n" + "=" * 65)
    print("4. SCENARIO C: SELF-CORRECTION DIAGNOSTICS")
    print("=" * 65)
    hallucinated_args = json.dumps(
        {
            "query_text": "AI",          # Too short (min_length=3)
            "top_k": 100,                # Out of bounds (le=50)
            "similarity_threshold": 1.5, # Out of bounds (le=1.0)
            "collection_name": "unknown_collection", # Invalid literal
            "hallucinated_key": "hallucinated_value", # Extra forbidden field
        }
    )
    res_c = engine.validate_and_dispatch("query_vector_index", hallucinated_args)
    print(f"[*] Response Status: success={res_c.success}")
    print("[*] Diagnostic Errors generated for LLM Self-Correction Prompt:")
    for err in res_c.errors:
        print(f"    - Field: {err['field']} | Input: {err.get('input')} | Issue: {err['message']}")


if __name__ == "__main__":
    run_simulation()
